export const GENRES_RU: { [key: string]: string } = {
  history: 'история',
  horror: 'ужасы',
  scifi: 'научная фантастика',
  'stand-up': 'стендап',
  fantasy: 'фэнтези',
  drama: 'драма',
  mystery: 'детектив',
  family: 'семейный',
  comedy: 'комедия',
  romance: 'романтика',
  music: 'музыкальный',
  crime: 'криминал',
  'tv-movie': 'тВ-фильм',
  documentary: 'документальный',
  action: 'боевик',
  thriller: 'триллер',
  western: 'вестерн',
  animation: 'анимация',
  war: 'военный',
  adventure: 'приключения',
};
